Chromium v137 for VIM boards
Signed-off-by: Gunjan Gupta <gunjan@wesion.com>

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -12,6 +12,24 @@ export DEB_BUILD_MAINT_OPTIONS+=optimize=-lto
 # indicate that binary targets do not require root
 export DEB_RULES_REQUIRES_ROOT=no
 
+-include /usr/share/dpkg/architecture.mk
+
+# cross-build support
+ifneq ($(DEB_BUILD_ARCH),$(DEB_HOST_ARCH))
+ifeq ($(filter cross,$(DEB_BUILD_PROFILES)),)
+$(error Please specify the "cross" build profile)
+endif
+export DEB_BUILD_OPTIONS+=crossbuildcanrunhostbinaries
+export HOST_EXEC_WRAPPER=qemu-$(DEB_HOST_ARCH_CPU)
+pkg_config_arch=$(subst i686,i386,$(DEB_HOST_GNU_TYPE))
+export PKG_CONFIG_LIBDIR=/usr/share/pkgconfig:/usr/lib/$(pkg_config_arch)/pkgconfig
+ifeq (armhf,$(DEB_HOST_ARCH))
+# avoid "Unable to find a guest_base to satisfy all
+# guest address mapping requirements" error
+export QEMU_GUEST_BASE=0x80000000
+endif
+endif
+
 # compile with clang (gcc is currently not supported)
 export AR=ar
 export NM=nm
@@ -20,6 +38,11 @@ export CXX=clang++-18
 
 # initial flags from dpkg-buildflags
 export DEB_CXXFLAGS_MAINT_STRIP=-g
+ifneq ($(filter armhf,$(DEB_HOST_ARCH)),)
+# clang gives us "argument unused during compilation" warnings for these
+export   DEB_CFLAGS_MAINT_STRIP+=-fno-stack-clash-protection
+export DEB_CXXFLAGS_MAINT_STRIP+=-fno-stack-clash-protection
+endif
 export CXXFLAGS:=$(shell dpkg-buildflags --get CXXFLAGS)
 export LDFLAGS:=$(shell dpkg-buildflags --get LDFLAGS)
 
@@ -47,11 +70,11 @@ defines:=clang_use_chrome_plugins=false
 
 # use system rust
 export RUSTC_BOOTSTRAP=1
-export CLANG_MVERS:=$(shell $(CC) --version | sed -n 's/.* clang version //p' | cut -d. -f1)
+export CLANG_MVERS:=$(shell $(CC) --version 2>/dev/null | sed -n 's/.* clang version //p' | cut -d. -f1)
 rust_sysroot=/usr/lib/rust-1.80
 defines+=rust_sysroot_absolute=\"$(rust_sysroot)\"
 defines+=rust_bindgen_root=\"/usr\"
-defines+=rustc_version=\"$(shell $(rust_sysroot)/bin/rustc --version)\"
+defines+=rustc_version=\"$(shell $(rust_sysroot)/bin/rustc --version 2>/dev/null)\"
 defines+=clang_base_path=\"/usr/lib/llvm-$(CLANG_MVERS)\"
 defines+=clang_version=\"$(CLANG_MVERS)\"
 
@@ -74,18 +97,15 @@ endif
 ifeq (armhf,$(DEB_HOST_ARCH))
 defines+=host_cpu=\"arm\" use_v4l2_codec=true use_vaapi=false arm_use_neon=true
 endif
-ifneq ($(filter arm64,$(DEB_BUILD_ARCH)),)
-# final link takes >150m, don't let Launchpad kill the build prematurely
-keepalive=debian/scripts/keepalive-wrapper.py 7200
-endif
-ifneq ($(filter armhf,$(DEB_HOST_ARCH)),)
-# clang gives us "argument unused during compilation" warnings for these
-export   DEB_CFLAGS_MAINT_STRIP+=-fno-stack-clash-protection
-export DEB_CXXFLAGS_MAINT_STRIP+=-fno-stack-clash-protection
+ifeq (ppc64el,$(DEB_HOST_ARCH))
+defines+=host_cpu=\"ppc64\" use_vaapi=true
 endif
 
-# thin lto requires >4 GB RAM, so avoid it on 32-bit architectures
-ifeq ($(filter armhf i386,$(DEB_HOST_ARCH)),)
+# final link takes >150m, don't let Launchpad kill the build prematurely
+keepalive=debian/scripts/keepalive-wrapper.py 7200
+
+# thin lto requires >4 GB RAM, so avoid it on 32-bit build hosts
+ifeq ($(filter armhf i386,$(DEB_BUILD_ARCH)),)
 defines+=use_thin_lto=true
 else
 defines+=use_thin_lto=false \
@@ -97,6 +117,7 @@ defines+=is_debug=false \
          use_sysroot=false \
          use_libjpeg_turbo=true \
          use_custom_libcxx=false \
+         optimize_webui=false \
          use_unofficial_version_number=false \
          safe_browsing_use_unrar=false \
          enable_vr=false \
@@ -109,6 +130,7 @@ defines+=is_debug=false \
          angle_build_tests=false \
          build_angle_perftests=false \
          treat_warnings_as_errors=false \
+         clang_warning_suppression_file=\"\" \
          use_qt5=false use_qt6=false \
          is_cfi=false \
          chrome_pgo_phase=0 \
@@ -179,9 +201,7 @@ override_dh_auto_configure: test_armhf_neon
 override_dh_auto_build-arch:
 	gn gen out/Release --args="$(defines)"
 	# XtraDeb workaround for https://crbug.com/40943790
-	# and https://issues.chromium.org/397258344
-	ninja -j$(njobs) -C out/Release ui/webui/resources/cr_components/history_clusters:build_ts \
-		obj/components/safe_browsing/content/common/proto/download_file_types_proto_gen.stamp
+	ninja -j$(njobs) -C out/Release ui/webui/resources/cr_components/history_clusters:build_ts
 	$(keepalive) ninja -j$(njobs) -C out/Release chrome chrome_sandbox content_shell chromedriver headless_shell
 	cp out/Release/chrome out/Release/chromium
 	cp out/Release/content_shell out/Release/chromium-shell
@@ -221,10 +241,16 @@ override_dh_auto_clean:
 
 ###################### upstream source downloading ############################
 
+ifdef FROM_GOOGLE
+# official distribution server
 url=https://gsdview.appspot.com/chromium-browser-official
+tarfile=$(extract)-lite.tar
+else
+url=https://github.com/chromium-linux-tarballs/chromium-tarballs/releases/download/$(version)
+tarfile=$(extract)-linux.tar
+endif
 version:=$(shell dpkg-parsechangelog -S Version | sed s/-.*//)
 extract=chromium-$(version)
-tarfile=$(extract)-lite.tar
 tarball=$(tarfile).xz
 debvers=../chromium_$(version)
 seconds=$(debvers).seconds
@@ -233,7 +259,7 @@ removed=$(debvers).files-removed
 options=--sort=name --owner=0 --group=0 --numeric-owner --mtime="@$$(cat $(extract)/build/util/LASTCHANGE.committime)" --clamp-mtime
 print_elapsed=echo $$(($$(date +%s) - $$(cat $(seconds)))) seconds
 minigbm_url=https://chromium.googlesource.com/chromiumos/platform/minigbm/+archive/refs/heads
-minigbm_tarball=release-R110-15278.B.tar.gz
+minigbm_tarball=release-R137-16267.B.tar.gz
 
 get-orig-source:
 	wget -nv --show-progress -c $(url)/$(tarball) -O ../$(tarball)
@@ -262,3 +288,19 @@ get-orig-source:
 	rm -rf $(extract)
 	@$(print_elapsed) | tee seconds
 	@mv -f seconds $(seconds)
+
+version_api_url='https://versionhistory.googleapis.com/v1/chrome/platforms/linux/channels/all/versions?filter=channel%3C=beta&order_by=version%20desc'
+
+check-version:
+	wget -q -O tmp.versions.json $(version_api_url)
+	@echo; echo 'Recent versions of Chromium for Linux:'
+	@jq -r '.versions[].name' tmp.versions.json \
+	 | head -n 10 | tr / '\t' | cut -f5,7 \
+	 | awk -v ver=$(version) '$$2 == ver {print $$0 "  <--- d/changelog"; next} {print $$0}'
+	@echo
+	@jq -r '.versions[].version' tmp.versions.json > tmp.versions.txt
+	@if ! grep -Fqx '$(version)' tmp.versions.txt; then \
+		echo 'Version "$(version)" in d/changelog not found!'; \
+		exit 1; \
+	fi
+	rm tmp.versions.*
